In [1]:
import pandas as pd
import os.path

# read map html from txt file
map_html = open(os.path.join(os.getcwd(), "DATA/map_html.txt"), "r").read()

In [3]:
# scrape the list of emotion dimensions
dimensions_html = map_html.split("axis")[1:]
dimensions = [axis.split('"')[1] for axis in dimensions_html]

In [4]:
# extract the html with category and dimension data
videos_html = map_html.split('"playx(&quot;')[1:]

In [5]:
# take chunk of html, strip out the dimensions data, return as series
def extract_dimensions_data(video_html):
    data = pd.Series([])
    data["Filename"] = video_html[:4]
    
    dimension_values = video_html.split("[")[1].split("]")[0].split(",")
    dimension_values = [float(value) for value in dimension_values]
    for dimension, value in zip(dimensions, dimension_values):
        data[dimension] = value
        
    return data

In [6]:
# apply to each video html chunk
dimensions_data = pd.Series(videos_html).apply(extract_dimensions_data).fillna(0)
dimensions_data.head()

,Filename,Approach,Arousal,Attention,Certainty,Commitment,Control,Dominance,Effort,Fairness,Identity,Obstruction,Safety,Upswing,Valence
0,0001,1.7,5.6,6.1,3.0,4.0,1.6,4.6,4.1,2.1,4.3,1.7,2.9,1.3,2.2
1,0002,3.8,5.3,6.2,4.7,4.2,4.8,5.1,3.1,4.2,4.3,3.0,4.1,4.0,3.7
2,0003,6.1,6.6,7.2,6.0,6.0,4.6,4.9,2.4,4.1,5.1,5.2,3.2,5.7,6.4
3,0004,4.2,4.3,5.1,5.2,4.2,5.6,3.9,2.3,5.2,5.7,4.9,2.2,6.2,5.1
4,0005,1.0,6.8,7.6,3.0,4.4,1.1,3.8,4.0,3.2,3.7,1.3,4.0,1.0,2.6

In [7]:
# take a single chunk of html, strip out the emotion category data and return that as a series
def extract_categories_data(video_html):
    data = pd.Series([])
    data["Filename"] = video_html[:4]
    
    category_percents = video_html.split("&quot;")[4].split("  +  ")
    for category_percent in category_percents:
        category = category_percent.split("% ")[1]
        percent = int(category_percent.split("% ")[0])
        fraction = percent / 100
        data[category] = fraction
        
    return data

In [8]:
# apply to each video html chunk
categories_data = pd.Series(videos_html).apply(extract_categories_data).fillna(0)
categories_data.head()

,Filename,Interest,Fear,Surprise,Confusion,Disappointment,Sadness,Aesthetic Appreciation,Anger,Anxiety,...,Calmness,Disgust,Entrancement,Relief,Satisfaction,Pride,Triumph,Envy,Craving,Contempt
0,0001,0.42,0.33,0.25,0.17,0.17,0.17,0.08,0.08,0.08,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0002,0.17,0.00,0.00,0.25,0.00,0.00,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0003,0.00,0.00,0.17,0.00,0.00,0.00,0.08,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0004,0.00,0.00,0.08,0.25,0.00,0.00,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0005,0.08,0.08,0.33,0.42,0.00,0.25,0.00,0.00,0.33,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0