In [2]:
import pandas as pd
import os.path
root_path = os.path.dirname(os.getcwd())

# Import video data
video_data = pd.read_csv(os.path.join(root_path, "DATA/video_data.csv"))
video_data.head()

,Filename,Admiration,Adoration,Aesthetic Appreciation,Amusement,Anger,Anxiety,Awe,Awkwardness,Boredom,...,vitality,vulnerability,warmth,weakness,weariness,wonder,worry,wrath,yearning,zeal
0,0001.mp4,0.000000,0.0,0.083333,0.00000,0.083333,0.083333,0.083333,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.00000,0.0,0.00000,0.0,0.0,0.0
1,0002.mp4,0.000000,0.0,0.000000,0.25000,0.000000,0.000000,0.000000,0.000000,0.083333,...,0.0,0.0,0.0,0.0,0.00000,0.0,0.00000,0.0,0.0,0.0
2,0003.mp4,0.083333,0.0,0.083333,0.66667,0.000000,0.000000,0.000000,0.083333,0.000000,...,0.0,0.0,0.0,0.0,0.00000,0.0,0.00000,0.0,0.0,0.0
3,0004.mp4,0.000000,0.0,0.000000,0.75000,0.000000,0.000000,0.000000,0.083333,0.000000,...,0.0,0.0,0.0,0.0,0.11111,0.0,0.00000,0.0,0.0,0.0
4,0005.mp4,0.000000,0.0,0.000000,0.00000,0.000000,0.333330,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.00000,0.0,0.11111,0.0,0.0,0.0

In [6]:
reference_values = [category.lower() for category in video_data.columns[1:]]

In [5]:
entities = pd.DataFrame([])

In [7]:
entities["reference_value"] = reference_values

In [10]:
entities.to_csv(os.path.join(root_path, "DATA/ree_category_entities.csv",), index=False, header=None)